[project]
name = "UI-design"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "chihyi liao",email = "chihyi.liao@gmail.com"},
]
dependencies = ["mplfinance>=0.12.10b0", "pyside6>=6.11.2", "matplotlib>=3.11.1"]
requires-python = ">=3.12, <=3.14"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]

[build-system]
requires = ["pdm-backend", "cython>=3.0.0", "setuptools>=61.0.0", "wheel"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true
package = false

[tool.pdm.build]
custom-hook =  "src/build.py"
run-setuptools = true
is-purelib = false
package-dir = "src"
includes = [
    "src"
]
excludes = [
    ".gitignore",
    "**/*.c",
    "**/*.cpp",
]

[tool.pyright]
venvPath = "."
venv = ".venv"
typeCheckingMode = "basic"
plugins = ["django-stubs"]


[tool.ruff]  # https://docs.astral.sh/ruff/settings/#top-level
line-length = 100
exclude = ["**/migrations/"]

[tool.ruff.lint]  # https://docs.astral.sh/ruff/settings/#lint
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "UP",  # pyupgrade
]
ignore = [
    "E402",  # module level import not at top of file
]

[tool.ruff.format]  # https://docs.astral.sh/ruff/settings/#format
quote-style = "double"

[dependency-groups]
dev = [
    "setuptools>=84.0.0",
    "cython>=3.3.0",
]
